### ISSUE TITLE
AttributeError: 'module' object has no attribute 'gate'

### ISSUE THREAD

**Issue by tagsys** [nikosl21/Gen2-UHF-RFID-Reader#1]
Dear Nikosl:

   I found such issue: "AttributeError: 'module' object has no attribute 'gate'" when I try to compile the source code. Do you have any idea about this error? Do I miss something?

Best

Lei

**Comment by nkargas** [comment]
Hello, I tried installing the software on another computer. I got the same error when I run the software without running "sudo ldconfig" first. You need to run sudo ldconfig once, after installing the software. This fixed the problem for me.

**Comment by tagsys** [comment]
Thank you very much! It works now. Appreciate your efforts and sharing.

**Comment by AdamLaurie** [comment]
Note this error will also be caused if you ran 'cmake' before you installed swig.

**Comment by trov4** [comment]
I'm getting a similar problem now where I get the output: 
```
[INFO] [UHD] linux; GNU C++ version 8.2.0; Boost_106700; UHD_3.13.1.0-3
[INFO] [B200] Detected Device: B200mini
[INFO] [B200] Operating over USB 2.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test...
[INFO] [B200] Register loopback test passed
[INFO] [B200] Setting master clock rate selection to 'automatic'.
[INFO] [B200] Asking for clock rate 16.000000 MHz...
[INFO] [B200] Actually got clock rate 16.000000 MHz.
[INFO] [B200] Asking for clock rate 32.000000 MHz...
[INFO] [B200] Actually got clock rate 32.000000 MHz.
Traceback (most recent call last):
  File "reader.py", line 122, in <module>
    main_block = reader_top_block()
  File "reader.py", line 90, in __init__
    self.connect(self.matched_filter, self.gate)
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 92, in __getattr__
    return getattr(self._impl, name)
AttributeError: 'top_block_sptr' object has no attribute 'gate'
```
Ran ldconfig and made sure to install swig and reinstall files, but still no luck in changing this.

**Comment by trov4** [comment]
Turns out by default line 76 is commented out on reader.py on master which is what led to this error. Not an issue with compiling this time!

Issue solved.
