### ISSUE TITLE
N310 Support

### ISSUE THREAD

**Issue by nolan876** [nikosl21/Gen2-UHF-RFID-Reader#11]
Does anyone know what it would take to port this project over to work on an N310?

**Comment by marxwolf** [comment]
I think it should work on N310, because N310 is much more expensive than N210(hahah). However, you might change some settings of the code to adapt N310.

**Comment by nolan876** [comment]
Do you know how to turn off the DC correction on an N310?  I cant seem to figure it out.

**Comment by SZY-CJJ** [comment]
Do you have a solution now? I'm currently porting the code on the N310. Looking forward to your reply.
