### ISSUE TITLE
sometime the transmitter does not send any signal 

### ISSUE THREAD

**Issue by Timothytrue** [nikosl21/Gen2-UHF-RFID-Reader#12]
Firstly, when I run the software, it is found that the transmitter does not send any signal and only the receiver is working all the time. The program can only trigger the behavior of transmitting signal under certain conditions. Normally it's supposed to be firing sine waves all the time.

Secondly, why does the RFX900 daughterboard need to call the function of set_auto_dc_offset(false) and SBX daughterboard doesn’t.

Looking forward for your rely! Best wishes for you!

**Comment by nkargas** [comment]
You are right. The transmitter logic depends on the received signal. If the reader is not able to decode a previously sent command then it will stop transmitting.  You can change this but it is not straightforward.

If I remember correctly, there wasn't any automatic DC offset correction when I was using the RFX900. Therefore, I did not need this command.

**Comment by nolan876** [comment]
How do I disable all logging? I have commented out all the GR_ lines but there are still some terminal outputs.

**Comment by Timothytrue** [comment]
I'm sorry, I have another question. How can I send the query signal for 10000 times not for 1000 times. I have changed the value of MAX_NUM_QUERIES for 10000 but it doesn't work.



---Original---

**Comment by sargoli** [comment]
> How do I disable all logging? I have commented out all the GR_ lines but there are still some terminal outputs.

After you extract the file,  go to lib and comment all GR_ and then start installation steps (create build folder and cmake ../ and ...)

**Comment by sargoli** [comment]
> I'm sorry, I have another question. How can I send the query signal for 10000 times not for 1000 times. I have changed the value of MAX_NUM_QUERIES for 10000 but it doesn't work.
> […](#)
> ---Original--- From: "Nikos Kargas"<notifications@github.com&gt; Date: Tue, Oct 20, 2020 06:54 AM To: "nkargas/Gen2-UHF-RFID-Reader"<Gen2-UHF-RFID-Reader@noreply.github.com&gt;; Cc: "Timothytrue"<1844782541@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [nkargas/Gen2-UHF-RFID-Reader] sometime the transmitter does not send any signal (#12) You are right. The transmitter logic depends on the received signal. If the reader is not able to decode a previously sent command then, it will stop transmitting. You can change it but it is not straightforward. If I remember correctly, when using RFX900 there isn't any automatic DC offset correction, that is why you do not need this line. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I changed the query before installation steps and then build, cmake ../, ....
It worked.
