### ISSUE TITLE
Does it suppose to fail ctest after make? (block does not work)

### ISSUE THREAD

**Issue by XDAChen** [nikosl21/Gen2-UHF-RFID-Reader#15]
I downloaded the package. ran configured, cmake and then make. It went through after some fixing ( reinstalling cmake3, doxygen..etc).
![image](https://user-images.githubusercontent.com/47087947/106338222-40983a00-6261-11eb-8905-99b93eb8691c.png)

And then I created a conf.conf to specify my XML file path at usr/local/share/gnuradio/grc/blocks. When I opened my GRC I was able to find the rfid_blocks.

However when I try to drag it to make a flow graph, there is error like this

![image](https://user-images.githubusercontent.com/47087947/106338759-a33e0580-6262-11eb-9cbe-ec454addcc38.png)

I suspected there were something wrong when compiling, so I ran a ctest in gr-rfid/build, but the result is not informative at all:

![image](https://user-images.githubusercontent.com/47087947/106338789-b224b800-6262-11eb-8b73-9fcfcdfafe6a.png)

I am using ubuntu 14 and gnuradio 3.7
anyone having similar trouble or any idea?
thanks in advance.

**Comment by yzhou-lab** [comment]
update the .xml file of every block you want to insert.

**Comment by yzhou-lab** [comment]
> I downloaded the package. ran configured, cmake and then make. It went through after some fixing ( reinstalling cmake3, doxygen..etc).
> ![image](https://user-images.githubusercontent.com/47087947/106338222-40983a00-6261-11eb-8905-99b93eb8691c.png)
> 
> And then I created a conf.conf to specify my XML file path at usr/local/share/gnuradio/grc/blocks. When I opened my GRC I was able to find the rfid_blocks.
> 
> However when I try to drag it to make a flow graph, there is error like this
> 
> ![image](https://user-images.githubusercontent.com/47087947/106338759-a33e0580-6262-11eb-9cbe-ec454addcc38.png)
> 
> I suspected there were something wrong when compiling, so I ran a ctest in gr-rfid/build, but the result is not informative at all:
> 
> ![image](https://user-images.githubusercontent.com/47087947/106338789-b224b800-6262-11eb-8b73-9fcfcdfafe6a.png)
> 
> I am using ubuntu 14 and gnuradio 3.7
> anyone having similar trouble or any idea?
> thanks in advance.

update the .xml file of every block. Use _gr_modtool makexml_ command after the first _cmake ../_ (cd Gen2-UHF-RFID-Reader/gr-rfid _gr_modtool makexml gate_ for example). Then rebuild.
