### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by tagsys** [nikosl21/Gen2-UHF-RFID-Reader#2]
I got a series of UOOOOOOOOOOOOO as shown in beneath. It seems that my PC speed cannot catch up the sampling rate, leading to the overflow. Do you have any idea how to deal with this issue?

==========================================================
Using Volk machine: avx2_64_mmx_orc
gr::log :INFO: gate0 - T1 samples : 96
gr::log :INFO: gate0 - PW samples : 4
gr::log :INFO: gate0 - Samples of Tag bit : 10
gr::log :INFO: gate0 - Size of window : 100
gr::log :INFO: gate0 - Size of window for dc offset estimation : 48
gr::log :INFO: gate0 - Duration of window for dc offset estimation : 120 us
gr::log :INFO: gate0 - Initializing reader state...
gr::log :INFO: tag_decoder0 - Number of samples of Tag bit : 10
gr::log :INFO: reader0 - Block initialized
gr::log :INFO: reader0 - Number of samples data 0 : 24
gr::log :INFO: reader0 - Number of samples data 1 : 48
gr::log :INFO: reader0 - Number of samples cw : 250
gr::log :INFO: reader0 - Number of samples delim : 12
gr::log :INFO: reader0 - Number of slots : 1
gr::log :INFO: reader0 - Carrier wave after a query transmission in samples : 1295
gr::log :INFO: reader0 - Carrier wave after ACK transmission in samples : 4575
-- Initializing core control...
-- Performing register loopback test... pass
-- Performing register loopback test... pass
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Performing CODEC loopback test... pass
-- Setting time source to internal
-- Asking for clock rate 16 MHz
-- Actually got clock rate 16 MHz
-- Performing timer loopback test... pass
-- Performing timer loopback test... pass
'Q' to quit 
UOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOUOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOqOOOOO

 --------------------------
| Number of queries/queryreps sent : 0
| Current Inventory round : 1
 --------------------------
| Correctly decoded EPC : 0
| Number of unique tags : 0
 --------------------------

**Comment by swadhin** [comment]
How did you solve this issue ? Are there any needed PC configuration ? I am not being able to implement the basic USRP based RFID reader setup.

**Comment by swadhin** [comment]
> I got a series of UOOOOOOOOOOOOO as shown in beneath. It seems that my PC speed cannot catch up the sampling rate, leading to the overflow. Do you have any idea how to deal with this issue?
> 
> ==========================================================
> Using Volk machine: avx2_64_mmx_orc
> gr::log :INFO: gate0 - T1 samples : 96
> gr::log :INFO: gate0 - PW samples : 4
> gr::log :INFO: gate0 - Samples of Tag bit : 10
> gr::log :INFO: gate0 - Size of window : 100
> gr::log :INFO: gate0 - Size of window for dc offset estimation : 48
> gr::log :INFO: gate0 - Duration of window for dc offset estimation : 120 us
> gr::log :INFO: gate0 - Initializing reader state...
> gr::log :INFO: tag_decoder0 - Number of samples of Tag bit : 10
> gr::log :INFO: reader0 - Block initialized
> gr::log :INFO: reader0 - Number of samples data 0 : 24
> gr::log :INFO: reader0 - Number of samples data 1 : 48
> gr::log :INFO: reader0 - Number of samples cw : 250
> gr::log :INFO: reader0 - Number of samples delim : 12
> gr::log :INFO: reader0 - Number of slots : 1
> gr::log :INFO: reader0 - Carrier wave after a query transmission in samples : 1295
> gr::log :INFO: reader0 - Carrier wave after ACK transmission in samples : 4575
> -- Initializing core control...
> -- Performing register loopback test... pass
> -- Performing register loopback test... pass
> -- Performing register loopback test... pass
> -- Performing CODEC loopback test... pass
> -- Performing CODEC loopback test... pass
> -- Setting time source to internal
> -- Asking for clock rate 16 MHz
> -- Actually got clock rate 16 MHz
> -- Performing timer loopback test... pass
> -- Performing timer loopback test... pass
> 'Q' to quit
> UOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOUOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOqOOOOO
> 
> ## | Number of queries/queryreps sent : 0
> | Current Inventory round : 1
> ## | Correctly decoded EPC : 0
> | Number of unique tags : 0

Can you please let me know how did you solve the issue ? What is the minimum requirement to make the system run in its default case ?

**Comment by kingyxz** [comment]
I also encountered this problem, can you share the solution?I will be grateful
