### ISSUE TITLE
Some detail about the daughterboard

### ISSUE THREAD

**Issue by kangqf** [nikosl21/Gen2-UHF-RFID-Reader#3]
Hi,Thank for your outstanding work for this repository. But I only have the WBX daughterboard but SBX or RFX 900. So can you help me how to modify the code or add some code to use this daughterboard. Thanks a lot.

**Comment by sshhsh** [comment]
Hello, I have the same problem. Could you please tell me whether you have any solutions about it? Thanks.

**Comment by xcluo** [comment]
If someone has solved this problem， I'm failed in decoding with WBX or SBX.

**Comment by swadhin** [comment]
I am also failing to decode with SBX daughterboard too. I am having some underflow. ANy luck or suggestion ?

**Comment by swadhin** [comment]
> If someone has solved this problem， I'm failed in decoding with WBX or SBX.

Did you find any solution regarding this ?
