### ISSUE TITLE
cannot get results 

### ISSUE THREAD

**Issue by Dongxuanjiang** [nikosl21/Gen2-UHF-RFID-Reader#6]
hi 
i try to run your code in offline mode in linux after install well,
by test the file named file_source_test ,
but i cannot get any resoults in the result file in misc/data,
the only thing i could see is  command line ;

| Number of queries/queryreps sent : 71
| Current Inventory round : 72
 --------------------------
| Correctly decoded EPC : 70
| Number of unique tags : 1
| Tag ID : 27  Num of reads : 70

how can i do to solve this problem?

**Comment by Philippek** [comment]
Did you manage to fix this problem? I have the same issue.
