### ISSUE TITLE
How can I add add files in lib?

### ISSUE THREAD

**Issue by whitecloudy** [nikosl21/Gen2-UHF-RFID-Reader#7]
I try to add some of my files in the 'lib' directory and use the class that I made. But every time I tried to call any function in the class at the 'tag_decoder.cc', 'reader.py' occurs AttributeError written below.

AttributeError: 'module' object has no attribute 'gate'

And of course when I erase what I wrote in 'tag_decoder.cc', this problem disappears...... Is there anyone can help me?

**Comment by Wangshuai8156** [comment]
Hi!Do you solve your problem? I am into the same problem.I hope to get help.thanks!

**Comment by whitecloudy** [comment]
I figured out that I insert some cmake code in wrong way...... That's all I understand and after I fixed it, it works normally.
